export const techList = [
  {
    id: 0,
    nom: "HILALI",
    email: "tarhisaid@gmail.com",
    job: "CPRV",
    active: true,
    atelierAffectation: "E-PARKING",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 555,
    nom: "ZAINAB",
    email: "",
    job: "CPRV",
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 1,
  },
  {
    id: 100,
    nom: "BASSIR",
    email: "",
    job: "CS",
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 1,
  },
  {
    id: 120,
    nom: "ESSAIH",
    email: "",
    job: "CS",
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 110,
    nom: "HILALI",
    email: "",
    job: "CS",
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 100,
    nom: "ELMOURZBANI",
    email: "",
    job: "CS",
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 1,
    nom: "Amine",
    email: "",
    job: "technicien",
    active: true,
    atelierAffectation: "express",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 2,
    nom: "Ilyass",
    job: "technicien",
    active: true,
    atelierAffectation: "express",
    availability: false,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 3,
    nom: "JAWAD",
    job: "technicien",
    active: true,
    atelierAffectation: "express",
    availability: false,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 4,
    nom: "RABIE",
    job: "technicien",
    active: true,
    atelierAffectation: "mecanique",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 5,
    nom: "Redouane",
    job: "technicien",
    active: true,
    atelierAffectation: "mecanique",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 6,
    nom: "Khalid",
    job: "technicien",
    active: true,
    atelierAffectation: "mecanique",
    availability: false,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 7,
    nom: "yassine",
    job: "technicien",
    active: true,
    atelierAffectation: "electrique",
    availability: true,
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 8,
    nom: "abdelmounime",
    job: "technicien",
    active: true,
    atelierAffectation: "electriue",
    availability: "off",
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 9,
    nom: "youness",
    job: "technicien",
    active: true,
    atelierAffectation: "bodyCar",
    availability: "off",
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 10,
    nom: "hassan",
    job: "technicien",
    active: true,
    atelierAffectation: "bodyCar",
    availability: "off",
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 11,
    nom: "AADIL",
    job: "technicien",
    active: true,
    atelierAffectation: "bodyCar",
    availability: "off",
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 12,
    nom: "ABDERRAZAK",
    job: "technicien",
    active: true,
    atelierAffectation: "bodyCar",
    availability: "off",
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
  {
    id: 13,
    nom: "abdelghafour",
    job: "technicien",
    active: true,
    atelierAffectation: "bodyCar",
    availability: "off",
    workingDayDuration: "5h",
    enAttente: 2,
    termines: 3,
  },
];
