export const techList = [
  {
    id: 999,
    nom: "HILALI",
    email: "tarhisaid@gmail.com",
    photo: "",
    job: "Pisteur",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 20,
    nom: "ZAINAB",
    email: "",
    job: "CPRV",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 21,
    nom: "BASSIR",
    email: "",
    job: "CS",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 22,
    nom: "ESSAIH",
    email: "",
    job: "CS",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 23,
    nom: "HILALI",
    email: "",
    job: "CS",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 24,
    nom: "ELMOURZBANI",
    email: "",
    job: "CS",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "showroom",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 1,
    nom: "Amine",
    email: "",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "express",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 2,
    nom: "Ilyass",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "express",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 3,
    nom: "JAWAD",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "express",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 4,
    nom: "RABIE",
    job: "technicien",
    active: true,
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "mecanique",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 5,
    nom: "Redouane",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "mecanique",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 6,
    nom: "Khalid",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "mecanique",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 7,
    nom: "yassine",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "diagnostic",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 8,
    nom: "abdelmounime",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "diagnostic",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 9,
    nom: "youness",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "carrosserie",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 10,
    nom: "hassan",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "carrosserie",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 11,
    nom: "AADIL",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "carrosserie",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 12,
    nom: "ABDERRAZAK",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "carrosserie",
    availability: true,
    workingDayDuration: "9h",
  },
  {
    id: 13,
    nom: "abdelghafour",
    job: "technicien",
    doingStartWorking: 9.5,
    toDo: 2,
    done: 3,
    hToDo: 3,
    hDone: 1.5,
    hDoing: 1,
    workDayHours: 9,
    cardsHistory: ["cardID1", "cardID2"],
    active: true,
    atelierAffectation: "carrosserie",
    availability: true,
    workingDayDuration: "9h",
  },
];
